- admin.ml
- admin.mli
- cache.ml
- cache.mli
- check.ml
- check.mli
- client.ml
- diff.ml
- diff.mli
- jbuild
- opam-check-all.opam
- server.ml
This branch keeps track of the progress on making an administration tool for the opam-check-all server. This allows several users to do checks without having access to the server itself.
cc @samoht
Identification is for the moment done by having one RSA private key per users on both sides because the `x509` library doesn't support public key format given by `ssh-keygen`. The only format accepted is `PKCS8` and can be converted from the default format with the following command:
```
$ ssh-keygen -e -f key.pub -m PKCS8 > key-pkcs8.pub
```
I might use `Nocrypto`'s internal key format (sexp) at one point anyway and use two key pairs to also encrypt the whole connection (for the moment the username is prefixed in clear text to know which key to use for the rest of the message).
cc @hannesm
> [WIP] Administration tool

- client/client.ml
- lib/dune
- lib/intf.ml
- lib/intf.mli
- lib/oca_lib.ml
- lib/oca_lib.mli
- lib/server_configfile.ml
- lib/server_configfile.mli
- lib/server_workdirs.ml
- lib/server_workdirs.mli
- opam-health-check.opam
- server/backend/backend.ml
- server/backend/check.ml
- server/lib/cache.ml
- server/lib/cache.mli
- server/lib/html.ml
- server/lib/server.ml
WIP experiment, code unfinished.
Potentially this would allow opam-health-check to:
* reduce its disk consumption by a factor of a 100 (e.g. for one run, from 7Go uncompressed to ~70Mo compressed)
* with negligible performance hit when reading a log file (the indexation allows to have almost no performance cost)
* and negligible performance hit when searching into log files (ideally same as above but more test is needed)
Will rely on https://github.com/vasi/pixz
> [WIP] Compress log files using pixz (indexed xz)

- lib/server_configfile.ml
- lib/server_configfile.mli
- server/backend/check.ml
- server/lib/cache.ml
This change does several things:
* Make the platform being checked configurable, by adding the `platform.os`, `platform.arch` and `platform.distribution` to the configuration file.
* rearrange the build script so that:
- the only directories used are `/tmp` and `~/` (aka. `$HOME`) and no fixed path to `/home/opam` anymore.
- removing the m4 dependency from `ocamlfind` (https://github.com/ocaml/ocamlfind/pull/13) so that no depext needs to be installed and removed (the later part is not being dealt with in opam depext)
Currently there are still a few observations:
- it seems to be relatively easy to have platform-agnostic (UNIX..) code. The only non-platform-agnostic code so far is the bit that prefixes the base image name by `ocurrent/opam:` on linux. If the macOS workers could discard …
> Make opam-health-check platform-agnostic

- server/lib/html.ml
Fixes https://github.com/ocurrent/opam-health-check/issues/8
> Filter out deprecated packages from the show-latest-only view

- server/lib/cache.ml
- server/lib/html.ml
- server/lib/html.mli
Main changes:
* Addition of the "about this run" info box (proposal by @mshinwell)
* Header on top of every pages for quick navigation to the main page, /diff and /run
* Some rewording of the filters
Before:
After:
> Improve UI

- server/backend/check.ml
- server/lib/server.ml
- server/lib/server.mli
This prompt the users opam-health-check to use the client command to check failures instead of expecting the server to print the debug logs using --debug
> Improve the user experience when encountering an error

- server/backend/admin.ml
- server/backend/admin.mli
- server/backend/backend.ml
- server/backend/check.ml
- server/backend/check.mli
- server/lib/cache.ml
- server/lib/cache.mli
Waiting for all the action to finish when refreshing the cache is a much sainer behaviour and avoids issues (race-conditions) and slow downs for people who go to the website while the cache is being refreshed
> Improve and avoid race condition with the cache

- lib/server_workdirs.ml
- lib/server_workdirs.mli
- server/backend/backend.ml
- server/lib/cache.ml
- server/lib/cache.mli
On the main instance of opam-health-check, RAM usage after the cache prefetching could reach 35% of RAM.
By default the OCaml GC can take up to 120% the current amount of RAM the program takes (see `Gc.space_overhead`), which means the program would reach 77% of RAM after a day or two. That's even without counting some of the lazy cache values that can be added to the total amount of memory taken when a user reaches for an older page (which bots do!)
This PR makes it so that the amount of memory taken is fixed (no more lazy) and much lower (down to 10.5% of RAM), which with OCaml's default 120% `space_overhead` value, the max amount of RAM taken is about 24% of total RAM on the machine.
> Fix OOM kill

- server/backend/check.ml
When the run starts, neither `opam-health-check log` nor querying the Web interface is very informative.
```
$ opam-health-check log
Sending command…
Getting packages list for 5.0.0…
Getting packages list for 5.0.0+more_volatile…
```
```
$ curl http://localhost:8080/
opam-health-check: no run exist, please wait for the first run to finish. Please look at the documentation to learn how to start it.
```
The idea here is to add an output line telling people to be patient for an hour or two.
> Add note to let users know about long startup time

- server/backend/check.ml
This PR adds support for macOS and FreeBSD.
```
platform:
os: freebsd
arch: x86_64
distribution: freebsd
```
```
platform:
os: macos
arch: x86_64
distribution: homebrew
```
As worker pools for these systems have a low capacity, it will not be practical to run these very frequently or against an extensive collection of compilers; however, limiting the selection to the latest compiler and package version may still provide some insights.  This `list-command` selects just the latest version.
```
list-command: opam list --available --installable --columns=package --short
```
These health checks can also be helpful when testing ocluster workers.
My latest run on FreeBSD can be seen here: http://freebsd-health-check.ocamllabs.io:8080/
> FreeBSD and macOS support

- server/backend/check.ml
Same as https://github.com/ocurrent/opam-repo-ci/pull/242
> Enable -warn-error +partial-match by default to ensure changes in a dependency do not lead into unforseen runtime failures

- Dockerfile
This PR adds the package `netbase`.  Without this package `opam-health-check` fails with the error `unknown scheme`
```shell
Sending command…
opam-health-check: internal error, uncaught exception:
Failure("resolution failed: unknown scheme")
Raised at Client.send_msg.(fun) in file "client/client.ml", line 48, characters 4-108
Re-raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3077, characters 20-29
Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 31, characters 10-20
Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 118, characters 8-13
Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 124, characters 4-13
Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
Called from …
```
> Add netbase

- client/client.ml
- server/backend/admin.ml
Dear valued opam-health-check authors and maintainers,
thanks to @reynir https://github.com/mirage/mirage-crypto/pull/208#issuecomment-1969277758 I got aware that your application uses the "convert a RSA key to s-expression" from mirage-crypto-pk. Now, this is a feature we'd like to remove from the next version.
What this PR provides is a possible migration. I'm not sure how opam-health-check is deployed and how the key material is generated / copied / provided.
What this PR does:
- on the key generation and writing of key files, it uses PEM (PKCS8) instead of s-expressions
- on the key reading (decoding) side, it first tries to decode as s-expression and if that fails as PEM
Now, depending on the deployment and desired use, of course there can as well be a utility that goes through the …
> store keys as pem instead of s-expression

- dune-project
- opam-health-check.opam
`docker_hub.0.2.0` has breaking changes, so use a version below that.
> Upper bound for `docker_hub`

- server/backend/check.ml
Helps with test suite integration when showing test logs.
> Define `CI` and `OPAM_HEALTH_CHECK_CI` env vars in runs

- Dockerfile
- client/client.ml
- opam-health-check.opam
- server/backend/admin.ml
While trying to install and build it on I ran across a couple of issues:
1. X509 1.0 changed API a bit so I updated to the new API. Fairly straightforward
2. capnproto-rpc 2.0 changed API quite significantly so for now I changed the constraint to avoid the issue.
> Build failure fix

- server/backend/check.ml
See https://windows.check.ci.dev
> Add Windows support

- .gitignore
Gitignoring _opam helps e.g. `rg` from finding hits in the local switch.
> Ignore OPAM local switch

- client/client.ml
- client/dune
- opam-health-check.opam
- server/backend/admin.ml
- server/backend/backend.ml
- server/backend/check.ml
- server/backend/dune
- server/dune
- server/lib/cache.ml
- server/lib/dune
- server/lib/server.ml
With Lwt 5.3 there is support for custom `let` operators so for the sake of readability this PR ports the code to them.
It's a bit of a shame that we don't have custom `match` operators, the remaining features of ppx_lwt like `[%lwt.finally]` or `try%lwt` are not quite as important IMHO. On the other hand, some code was able to use `let+` so a couple of `Lwt.returns` could be scrapped.
In any case this should make it a bit more feature-proof and speed up the build slightly.
> Port from custom PPX to let operator

- opam-health-check.opam
- server/backend/backend.ml
It seems mirage-crypto 2.0 will [remove these packages](https://github.com/mirage/mirage-crypto/blob/main/CHANGES.md#v200-2025-02-03) but for now it is fairly easy to migrate.
> Update to mirage-crypto 1.2+ API

- lib/dune
- lib/oca_lib.ml
- lib/server_configfile.ml
- lib/server_workdirs.ml
In #77 I apparently forgot to remove all ppx_lwt, so the linter rightfully complained that I shouldn't have removed ppx_lwt from the dependencies.
This removes the remaining occurences.
> Remove rest of ppx_lwt

- lib/server_configfile.ml
- lib/server_configfile.mli
- server/backend/check.ml
This adds an option `build-with` which defaults to `opam` at which point it will do the exact same as before. If set to `dune` it will emit different OBuilder instructions to download the sources using `opam` and build them and their dependencies using `dune`.
Some optimizations could be done (e.g. there is no need for a switch in the builder images, however it is cached so the impact isn't too big) but for now this is some starting point that should allow a run and collecting results.
It was tested successfully with `list-command: echo tqdm.0.1` and built the package just fine.
> Allow building packages via Dune with a new option

- server/backend/check.ml
A bunch of packages are failing to build, because their tests dependencies are incorrectly specified and/or warnings are treated as errors in the default dune profile. These errors are not really related to dune package management, so perhaps we can be less strict in the healthcheck to help reduce the number of packages we need to look at.
> Check dune build for installs only

- server/backend/check.ml
This prevents dune from picking a different OPAM repo commit than the image and OPAM would do.
> Use a specific OPAM repo revision for the workspace

- server/backend/check.ml
The reasoning here is that package metadata in the tarball is often invalid and the failures don't really reflect whether the packages build correctly. This is often due to new packages being released which require version constraints applied retroactively or just forgotten dependencies. opam-repository fixes these packages continulously so this PR:
1. Replaces the `opam` files from the tarballs with the ones that `opam` would use.
2. Removes the `package` stanzas from `dune-project` to force Dune to use the dependency information from the OPAM files.
> Use OPAM-repo metadata when attempting to build a package

- server/backend/check.ml
We currently build all the packages in a repository when testing but that will fail all packages in the selection even if just a single package fails to build.
As such this PR aims to reduce the amount of packages that are being built by doing some creative reshuffling.
The reason why it is so complicated is because when we want to build with `--only-packages` we have to make sure to include the local packages that (might) be required (think `foo` and `foo-lwt` which depends on `foo` or for a more real-life example `yojson` and `yojson-five`) but we can't include every package because unrelated packages (`yojson-bench` in my testing example) will fail to build, thus marking all the packages as failures, despite no dependency between them (`yojson-five` doesn't care about `yojson-bench`).
> Only build the specified package

- server/backend/check.ml
The issue is that `sexpdata` parses numbers, so something like `(dune lang 1.10)` is parsed as floating point and reduced to `(dune lang 1.1)` which turns the dune-file invalid in some cases.
`sexp` is an OCaml tool from Jane Street, unfortunately it doesn't allow matching and deleting, only matching and rewriting so we rewrite using `sexp` and delete using `grep` in an additional step.
> Use JaneStreet `sexp` instead of `sexpdata`

- server/backend/check.ml
This extends the build commands with an additional error path that will fail the build if the solver can't find a solution. In such case it will error with a specific error message that the clasifier will pick up and give a different failure reason.
Inspired by #92.
> Differentiate between solve and build failures

- client/client.ml
- lib/intf.ml
- lib/intf.mli
- lib/server_configfile.ml
- lib/server_configfile.mli
- server/backend/admin.ml
- server/backend/check.ml
As this was requested by a few people including @samoht I spent some time moving the `build-with` option to the OCaml switch list. That means that it is possible to configure a switch like `5.3` to build with opam and `5.3+dune` that will build the packages with Dune.
It extends the client and admin protocol a little to be able to pass the `build-with` option around.
> Move `build-with` to a per-switch option

- server/backend/check.ml
This change avoids tests being built if they're not used. It should fix a lot of Jane Street packages.
We added support for lockfiles and `--release` mode recently and it is supported by the preview binaries so we should be able to use that in the health check now.
> Use `--release` instead of `--profile=release`

- server/backend/check.ml
The way we massage projects to use the most recent metadate is that we collect the list of packages in the project from OPAM files and remove the `package` entries in `dune-project`.
This works well, but some packages, e.g. CPPO don't ship with `.opam` files at all (they're not required for building a project). However as we remove the `package` stanzas (to make the solver pick the dependencies from the OPAM-repository metadata) then Dune doesn't know what packages exist if there are no `.opam` files and fails.
This code attempts to determine what packages exist in the project by loading the package names from both `.opam` files that exist in the source archive and the `dune-project` before deleting the entries in a later step.
> Handle packages without OPAM files in source archives

- server/backend/check.ml
The code would accidentally pick package names that are subsets of other packages. For example if the package was `lab`, it would be matched if `gitlab` was in the file, thus spuriously including `lab` in the packages that are to be built.
This fixes the `gitlab` package and also probably some of the `ffmpeg-*` packages, which seem to exhibit a similar error message.
> Match selected packages against full package name, not just subsets

- lib/intf.ml
- lib/intf.mli
- lib/server_configfile.ml
- lib/server_workdirs.ml
- lib/server_workdirs.mli
- server/backend/admin.ml
- server/backend/check.ml
This PR clears up the names in `Intf.Switch` which mixes up the name of the switch and the name of the compiler. This lead to the issue that the temporary directories are named after the compiler versions, when it would be better to use the name of the switch to index into the file system. That way the same compiler can be used to build using OPAM and Dune as long as the switch name differs.
Obsoletes and incorporates #100.
> Compiler name switcheroo

- server/backend/check.ml
Some packages (e.g. `acp4`) have `conf-*` packages in `depopts` thus the depext calculation doesn't factor them in. They should probably be added to ensure as much of the project can be built.
> Add `depopts` to `depext` calculation

- server/backend/check.ml
`opam install ./ --depext-only` failure returns an exit code 0, so the script was not getting terminated. This patch checks for an error and fails if it's the case. Needs to be rebased on top of #102 when it's merged.
> Exit in case of opam install error

- server/backend/check.ml
The issue here is that OPAM does not install depopts by default and even despite #102 picking depopts explicitely this only works if the depopts are in the repo. E.g. if a package depends on a package that has a depopt itself, it won't be detected by #102 and OPAM won't suggest the `depext`. However, Dune will pick it when locking and then fail.
Thus this code changes the logic, so Dune locks a solution first and is then used to output the packages that need to be installed.
> Use Dune to determine depexts

- server/backend/check.ml
As I was writing that we don't support `dune-site` because to read the dependencies out of `opam` files we need to delete the `package` stanzas out of `dune-project` it hit me that we probably can reinstate the original `dune-project` file (with the sites declarations) after the `dune pkg lock` because afterwards Dune doesn't care about the dependencies anymore.
This should work as long as the packages for which `.opam` files exist and the `package` stanzas align. Given we do our best to determine these by reading them from the tarball and `dune-project`, I think this should be the case for all packages.
I've tested it against `camomile.2.0.0` (one of the [packages that fail due to sites](https://dune.check.ci.dev/?comp=5.3-dune&comp=5.3-opam&available=5.3-dune&available=5.3-opam&show-only …
> Fix compilation of dune-sites by reinstating site information
